apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-service
spec:
  rules:
  - host: go-service.rancher.localhost
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: go-service
            port:
              number: 8080
  tls:
  - hosts:
    - go-service.rancher.localhost