apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.name | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
  selector:
    app: {{ $.Values.name }}